version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - ":robot: bot"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - ":robot: bot"
